name: Repo Refresh

on: [repository_dispatch]

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Run repo.json builder
        run: node ./builder/index.js

      - name: Commit and push repo.json.
        run: |
          git config --global user.name "Actions User"
          git config --global user.email "actions@github.com"
          git fetch origin main
          git checkout main
          git add repo.json
          git commit -m "[CI] Update repo.json" || true
          git push origin main