name: Repo Refresh

on: [repository_dispatch]

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Run repo.json builder
        run: node ./builder/index.js
